### ISSUE TITLE
README.md python -m SimpleHTTPServer doesn't work

### ISSUE THREAD

**Issue by inodb** [cBioPortal/oncoprintjs#15]
When following the instructions in the readme serving the page using Python's SimpleHTTPServer doesn't work:

```
cd dist/test && python -m SimpleHTTPServer
```
![screen shot 2015-05-19 at 12 01 25 pm](https://cloud.githubusercontent.com/assets/1334004/7707655/d3c81258-fe1e-11e4-809d-6165e8d8fd88.png)

The JS error is:
```
test-oncoprint-bundle.js:1323 Uncaught SyntaxError: Unexpected token ILLEGAL
localhost/:31 Uncaught ReferenceError: testscript is not defined
```

No problems using ``http-server`` though.

**Comment by gideonite** [comment]
Thanks for reporting this! I'm sorry that we haven't gotten back to you sooner.

Unfortunately, I haven't been able to reproduce this issue. I have done the following:

```sh
$ gulp clean
$ gulp spec
$ gulp test
$ cd dist/test
$ python2.7 -m SimpleHTTPServer
```
I then navigate my browser to `localhost:8000` and the page loads normally. I haven't seen any of the JS errors that you mentioned. Does this work for you? Perhaps we should specify the python version in the instructions.

**Comment by gideonite** [comment]
NVM. I now see that the problems appears when using Firefox.

**Comment by gideonite** [comment]
@inodb it's be great if you can pull 41c50f4 and see if that fixes the issue for you. Keep the bugs coming!

**Comment by inodb** [comment]
@gideonite Works now, looks the same as what I get with ``http-server`` now
![screen shot 2015-06-04 at 7 36 32 pm](https://cloud.githubusercontent.com/assets/1334004/7997065/8c4dbc28-0af5-11e5-936b-458ed97706d4.png)
