### ISSUE TITLE
Track labels overlap tracks on firefox

### ISSUE THREAD

**Issue by inodb** [cBioPortal/oncoprintjs#16]
Track labels are on top of the tracks in firefox instead of side by side in chrome.

![screen shot 2015-05-19 at 12 03 31 pm](https://cloud.githubusercontent.com/assets/1334004/7707730/474937b6-fe1f-11e4-9050-3e148f3e5c3b.png)

**Comment by gideonite** [comment]
Thanks for reporting this. The iron is very much still hot so I'm sure that this will be addressed as development continues. @adamabeshouse @jjgao Should we close this issue?

**Comment by adamabeshouse** [comment]
@gideonite @inodb Yeah, with the new table structure this is obsolete.
