### ISSUE TITLE
License change to AGPL?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/oncoprintjs#17]
The code of cBioPortal is licensed as AGPL. This is licensed as ISC. Should we change the license or do we prefer the more permissive license for oncoprint? I'm just opening this issue because I've heard different things from @n1zea144 and @jjgao. Including @adamabeshouse @gideonite in the discussion.

**Comment by gideonite** [comment]
Have we made a decision on this? If so, we may as well close the issue.

**Comment by gideonite** [comment]
^ @adamabeshouse @jjgao @n1zea144

**Comment by gideonite** [comment]
The discussion is proceeding by email and telephone calls.
