### ISSUE TITLE
missing 'gl-matrix' as dependency in package.json

### ISSUE THREAD

**Issue by makkBit** [cBioPortal/oncoprintjs#24]
'gl-matrix' package required by [oncoprintwebglcellview.js](https://github.com/cBioPortal/oncoprintjs/blob/master/src/oncoprintwebglcellview.js) is not listed as dependency in [package.json](https://github.com/cBioPortal/oncoprintjs/blob/master/package.json).
Due to this, `npm install` would result in the following error: `Error: Cannot find module 'gl-matrix'`

**Comment by adamabeshouse** [comment]
fixed
https://github.com/cBioPortal/oncoprintjs/commit/f42a2361f158cebb0089a4e99905d7808e9cae69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R42
